version: '2'
services:

#Zookeeper Service.
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: "no"
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper

#Kafka Service
  kafka:
    image: 'bitnami/kafka:latest'
    restart: "no"
    ports:
      - '9092:9092'
      - '29092:29092'
      
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      
    container_name: kafka-broker
    
    depends_on:
      - "zookeeper"

# MariaDB Service
  streaming-mariadb:
    image: mariadb:latest
    restart: on-failure
    ports:
      - '33306:33306'
    environment:
      MYSQL_ROOT_PASSWORD: streaming
      MYSQL_DATABASE: streaming
      MYSQL_USER: streaming
      MYSQL_PASSWORD: streaming

    volumes:
      - ${PWD}/mariadb:/var/lib/mysql

    container_name: streaming-mariadb

# Redis Service
  streaming-redis:
    image: redis:latest
    ports:
      - '6379:6379'

    container_name: streaming-redis